### ISSUE TITLE
Payment Module Not Showing in Frontend

### ISSUE THREAD

**Issue by rullymartanto** [uchenic/magento2-module-payment-tmrobokassa#4]
Hey I am new on magento,.. 
your payment module not display in frontend page,.
can you help ?
And module has been enable and has upgrade:setup too

Thanks
![image](https://cloud.githubusercontent.com/assets/5577057/18343346/3199b3e6-75dd-11e6-8e30-7816f1a81485.png)

**Comment by uchenic** [comment]
I guess you need to specify with which shipping method this payment method can be used in settings.
